### ISSUE TITLE
not issue, question

### ISSUE THREAD

**Issue by JeffreySarnoff** [mfalt/EllZeroTrendFiltering.jl#10]
What would happen if, in addition to quadratics, cubics were used?

**Comment by mfalt** [comment]
You mean as in defining the problem
`min sum_k (|f[k] - g[k]|)^3`, or in the continuous case
`min integrate_t (|f(k) - g(t)|)^3`
instead of 2 norm?

**Comment by mfalt** [comment]
Although, it might be possible to solve this using piecewise cubic functions, I am not sure if they retain the nice property of being possible to represented in a efficient minimal way or if the recursion step would actually work. The related paper for this code can be found at https://arxiv.org/pdf/1806.11041.pdf

**Comment by JeffreySarnoff** [comment]
Suppose [src/types](https://github.com/mfalt/EllZeroTrendFiltering.jl/tree/master/src/types) had two subdirectories `src/types/quadratic` and `src/types/cubic`, where `quadratic/` holds the source files currently available under `types/` (except `transition_costs.jl`) and `cubic/` holds `CubicPolynomial.jl`, `CubicForm.jl`, `PiecewiseCubic.jl`.  `src/types` holds a revised `transition_costs.jl` that handles quadratic and cubic forms, as may be appropriate.

With this, what would become more readily doable that is not easily done already?  How would the example solutions (their plots) change as one relied on (a) and admixture of quadratic and cubic or (b) more heavily on cubic?  [do not ask "in what way" -- that is part of my question]

**Comment by mfalt** [comment]
The reason for having Quadratics in the code is that Piecewise-Quadratics occur naturally as a result of the problem formulation. So given the original problem formulation, I can't see anything that would benefit from begin able to work with Cubics.

However, given some other problem formulation (maybe the one I stated above), if the problem can be reduced to a dynamic programming problem on the form
`V^m_i(y) = min_{ip} ( min_{yp} ( l_{i,ip}(y,yp) + V^{m-1}_i(yp) )` as equation (6a) from the acticle, but where `V` is piecewise cubic, and the transition costs `l` are CubicForms, then it might be possible to use this algorithm. 
This would require implementing the crucial function `add_cubic!` from `solve.jl`, corresponding to
```
"""
    add_quadratic!(Λ::PiecewiseQuadratic{T}, μ::QuadraticPolynomial{T}) where {T}
Inserts a quadratic polynomial μ into the linked list `Λ`, which represents a piecewise
quadratic polynomial, so that the new `Λ` satisfies
`Λ(y) := min{ Λ(y) ,μ(y) } ∀ y`
"""
```
as well as `poly_minus_constant_is_greater`
```"""
Given a piecewise quadratic V_Λ represented by Λ, a polynomial μ, and a real number ζ
this function evaluates if
μ(y) > V_Λ(y) + ζ  ∀ y
"""
```
and some other simpler functions.

With these in place, I guess it would be, in theory, possible to solve problems that reduce to the equation (6a) as stated above.

However, than main reason that our algorithm works well is that the number of Quadratics that we need to keep track of in each of the PiecewiseQuadratics grows linearly (!) with the problem size (although we still lack a formal proof for this). When working with Cubics, it might instead be that it grows combinatorially instead.

So I can't really answer your questionon how the result of the example plots would change, since the plots we have are a direct result on the problem formulation. If it is the case that a cubic cost can be rewritten on this form, then the result would simply penalize large deviations even more. It is worth noting that efficient algorithms exist for the problem where the cost is not the quadratic, but the maximum deviation over the sequence (Inf-norm).

**Comment by JeffreySarnoff** [comment]
that is a good answer
